plugins: /verdaccio/plugins
storage: /verdaccio/storage

auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd

uplinks:
  npmjs:
    url: https://registry.npm.taobao.org/

middlewares:
  audit:
    enabled: true

packages:
  '@*/*':
    access: $authenticated
    publish: $authenticated

  '**':
    access: $authenticated
    publish: $authenticated

logs:
  - { type: stdout, format: pretty, level: trace }
